name: Release Compile

on:
  push:
    branches:
      - main

jobs:
  release-job:
    name: Release gitgo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --production

      - name: Compile project
        run: bun run compile

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/gitgo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the release URL
        run: echo "Release URL: ${{ steps.create_release.outputs.upload_url }}"

